version: '3.9'

services:
  app:
    container_name: balance-app
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - bm-backend

  database:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - bm-backend

networks:
  bm-backend:
    driver: bridge

volumes:
  pg-data: